name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:16
        ports:
          - 3001:3001
        options: >-
          --health-cmd="curl -f http://localhost:3001 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Start the development server
      run: yarn dev &
      env:
        CI: true

    - name: Wait for server to be up
      run: npx wait-on http://localhost:3001

    - name: Run unit tests
      run: yarn test:unit

    - name: Run e2e tests
      run: yarn test:e2e

    - name: Build the project
      run: yarn build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "amuvavi@gmail.com"
        git config --global user.name "amuvavi"
        git add dist -f
        git commit -m "Deploy to GitHub Pages"
        git push origin `git subtree split --prefix dist main`:gh-pages --force
