name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:16
        options: --entrypoint /bin/sh

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Start the development server
      run: npm run start &
      continue-on-error: true

    - name: Wait for server to be up
      run: sleep 10

    - name: Run unit tests
      run: npm run test:unit

    - name: Run e2e tests
      run: npm run test:e2e

    - name: Build the project
      run: npm run build

    - name: Output Docker logs on failure
      if: failure()
      run: |
        echo "Container logs:"
        docker ps -a
        docker logs $(docker ps -a -q --filter "ancestor=node:16")
