name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:16
        ports:
          - 5173:5173

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Install Playwright browsers
      run: yarn playwright install

    - name: Verify vitest installation
      run: yarn list vitest

    - name: Start the development server
      run: |
        yarn dev > server.log 2>&1 &
        sleep 5
        cat server.log

    - name: Wait for server to be up
      run: |
        for i in $(seq 1 60); do
          curl -s http://127.0.0.1:5173 > /dev/null && break
          echo "Waiting for server... ($i)"
          sleep 1
        done
        curl -s http://127.0.0.1:5173

    - name: Run unit tests
      run: yarn test:unit

    - name: Run e2e tests
      run: yarn test:e2e

    - name: Build the project
      run: yarn build

    - name: List build directory contents
      run: ls -al ./dist  # Verify the contents of the build directory

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Ensure gh-pages branch exists
      run: |
        git fetch origin
        if ! git rev-parse --verify origin/gh-pages; then
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages
        fi

    - name: Checkout gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Force add build files
      run: |
        cp -r ./dist/* .
        git add --all
        git commit -m "deploy: ${{ github.sha }}" || echo "Nothing to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist  # Adjust this if your build output directory is different