name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:16
        ports:
          - 5173:5173

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Install Playwright browsers
      run: yarn playwright install

    - name: Verify vitest installation
      run: yarn list vitest

    - name: Start the development server
      run: |
        yarn dev > server.log 2>&1 &
        sleep 5
        cat server.log

    - name: Wait for server to be up
      run: |
        for i in $(seq 1 60); do
          curl -s http://127.0.0.1:5173 > /dev/null && break
          echo "Waiting for server... ($i)"
          sleep 1
        done
        curl -s http://127.0.0.1:5173

    - name: Run unit tests
      run: yarn test:unit

    - name: Run e2e tests
      run: yarn test:e2e

    - name: Build the project
      run: yarn build
    - name: List build directory contents
      run: ls -al ./dist  


  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist  